server.port=8085
spring.application.name=MABARCU
spring.datasource.url=jdbc:h2:file:./data/mabarcu_h2;MODE=PostgreSQL;DATABASE_TO_UPPER=false
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.main.web-application-type=servlet
logging.level.org.springframework.security=ERROR

spring.main.banner-mode=off
server.error.include-message=always
